### ISSUE TITLE
error for HTML

### ISSUE THREAD

**Issue by stardiviner** [Lompik/x-path-walker#4]
When I query path in HTML buffer (which is in `web-mode`) :

``` html
<!DOCTYPE HTML>
<html>
  <head>
    <meta encoding="utf-8">
  </head>
  <body>

    <p id="hello">Hello, World!</p>

  </body>
</html>
```

I got this error:

```
PATH-WALKER
Traceback (most recent call last):
  File "/usr/lib64/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/stardiviner/.emacs.d/elpa/x-path-walker-20160822.1015/xpathwalker/__main__.py", line 15, in <module>
    main(sys.argv[1:])
  File "/home/stardiviner/.emacs.d/elpa/x-path-walker-20160822.1015/xpathwalker/__main__.py", line 11, in main
    parse_args(argv)
  File "/home/stardiviner/.emacs.d/elpa/x-path-walker-20160822.1015/xpathwalker/args.py", line 70, in parse_args
    proc.parse_file(inputfile)
  File "/home/stardiviner/.emacs.d/elpa/x-path-walker-20160822.1015/xpathwalker/lxml_Processor.py", line 85, in parse_file
    self.parsed = lxml.etree.parse(file)
  File "src/lxml/lxml.etree.pyx", line 3427, in lxml.etree.parse (src/lxml/lxml.etree.c:79841)
  File "src/lxml/parser.pxi", line 1793, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:116175)
  File "src/lxml/parser.pxi", line 1819, in lxml.etree._parseDocumentFromURL (src/lxml/lxml.etree.c:116525)
  File "src/lxml/parser.pxi", line 1723, in lxml.etree._parseDocFromFile (src/lxml/lxml.etree.c:115413)
  File "src/lxml/parser.pxi", line 1126, in lxml.etree._BaseParser._parseDocFromFile (src/lxml/lxml.etree.c:110110)
  File "src/lxml/parser.pxi", line 584, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:103584)
  File "src/lxml/parser.pxi", line 694, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:105238)
  File "src/lxml/parser.pxi", line 624, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:104147)
lxml.etree.XMLSyntaxError: Opening and ending tag mismatch: meta line 4 and head, line 5, column 10
```

**Comment by Lompik** [comment]
thanks for the report.

Should be fixed  with 3b01dbd.

Regards,
lompik
